### ISSUE TITLE
[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/openshift-applier#132]
I am trying to process and apply a template that is located on my openshift cluster. I am using applier 2.0.9 and my task looks like

```
- object: jenkins-mycompany
  content:
  - name: "deploy mycompany jenkins image"
    template: "openshift//mycompany-jenkins"
    params: "{{ inventory_dir }}/../.openshift/params/mycompany-jenkins"
    tags:
      - sbx
      - build
```
The error I am receiving:

```TASK [openshift-applier : Determine location for the file] ************************************************************************************************************
objc[6472]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[6472]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.```
```

This only happens when a template is already on the cluster and not local to my project.
