### ISSUE TITLE
we should support `action: get`

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-applier#134]
When writing automation for kubernetes, we often need the ability to grab the value of a field in a resource and use that value in another resource. Applier should support this. Here are a few examples I can think of:

```
cluster_id=$(oc get machinesets -n openshift-machine-api -o jsonpath='{.items[0].metadata.labels.machine\.openshift\.io\/cluster-api-cluster}')
oc process -f machineautoscaler-template.yaml -p CLUSTER_ID=${cluster_id} | oc apply -f -
```

**Comment by oybed** [comment]
@etsauer for your two examples, what do you think about an applier inventory like the following? Does this align with what you were thinking? 

```
openshift_cluster_content:
- object: Machine Autoscaler
  content:
  - name: Fetch cluster id from running cluster
    action: get
    get_vars:
      kind: machinesets
      namespace: openshift-machine-api
      jsonpath: '{.items[0].metadata.labels.machine\.openshift\.io\/cluster-api-cluster}'
  - name: Apply machine autoscaler template
    template: "http://some-url.com/machineautoscaler-template.yaml"
    namespace: openshift-machine-api
    params_from_vars:
      CLUSTER_ID: "{{ get_output_machinesets_openshift_machine_api }}"
- object: Fetch and apply secret / token
  content:
  - name: Fetch builder SA secret name
    action: get
    get_vars:
      kind: sa
      name: builder
      namespace: somenamespace
      jsonpath: '{.secrets[0].name}'
  - name: Fetch secret content based on secret name
    action: get
    get_vars:
      kind: secret
      namespace: somenamespace
      name: "{{ get_output_sa_builder_somenamespace }}"
      jsonpath: '{.data.token}'
  - name: Apply secret template
    template: "http://some-url.com/secret-template.yaml"
    params_from_vars:
      TOKEN: "{{ get_output_secret_somenamespace }}"
```
