### ISSUE TITLE
Applier processes variables too early, making it difficult to use a pre-role for discovery purposes

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-applier#137]
I would like to have the ability to do discovery at some phase of an applier run. The purpose of this would be to be able to pull some values out of the kube api and use them as parameters to templates later in the run.

For example, let's say I have a pre-role that does this:

```
- name: Get Cluster Info
  k8s_facts:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: cluster_info

- name: Set Cluster Info Facts
  set_fact:
    infraid: "{{ cluster_info.resources[0].status.infrastructureName }}"
```

Then in my applier inventory I pass this `infraid` to a template:
```
  - name: MachineAutoscaler zone a
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ infraid }}"
```

 The problem with this is the fact that when we execute a loop over our `openshift_cluster_content` dictionary, the execution of the loop processes all of the variable templates in our dictionary. So by the time the pre-role tasks run, the "{{ infraid }}" template has already been evaluated.

I would like to propose we rethink how we execute this looping so that we can do "just in time" jinja processing.

This will also come into play with #134 

@oybed @tylerauerbeck @jkupferer
