### ISSUE TITLE
Support namespace at the object level

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-applier#15]
Example:

```
- object: Set up Image Builds
  namespace: image-builds
  content:
  - name: Create Image Builds Project
    template: "{{ inventory_dir }}/../templates/project.yml"
    params: "{{ inventory_dir }}/../params/image-management-project"
    template_action: create
```

@oybed @pabrahamsson
