### ISSUE TITLE
Option to create params from ansible variables

### ISSUE THREAD

**Issue by pcarney8** [redhat-cop/openshift-applier#25]
```
ci_cd:
  namespace: psc-ci-cd
  namespace_display_name: blah blah blah

openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params_from_vars: "{{ ci_cd }}"
    tags:
    - projects
```

Have applier enumerate the ansible variable `ci_cd` into params. Where each key (aka `namespace`) and value (`psc-ci-cd`) turn into either a temporary param file, or a string, like so `NAMESPACE=psc-ci-cd`

The `oc process` command could take it in via that temp file a string like so:
```
$ oc process -f my-rails-postgresql \
    -p POSTGRESQL_USER=bob \
    -p POSTGRESQL_DATABASE=mydatabase \
    | oc create -f -
```

These params ansible variables could/would still be stored in a `params/` directory, but because they are now ansible vars we can use all the benefits of ansible instead of them being in static formats
