### ISSUE TITLE
We should adopt the k8s_raw and oc_process modules

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-applier#39]
I believe the [k8s_raw](https://docs.ansible.com/ansible/2.5/modules/k8s_raw_module.html) module is now in a place where we could adopt it in openshift-applier. There is also an [oc_process](https://github.com/openshift/openshift-ansible/blob/master/roles/lib_openshift/library/oc_process.py) module in openshift-ansible right now. Between the two, they should provide the functionality we need to remove the hard dependency on `oc`.

Obviously, the hosting of the process module in openshift-ansible is problematic, as that creates a new, fairly heavy dependency for applier, so we'll want to inquire as to the roadmap/vision for that module, and see if we can influence that. Currently I see no module that provides the process functionality in ansible proper.

**Comment by pcarney8** [comment]
FYI, [k8s](https://docs.ansible.com/ansible/latest/modules/k8s_module.html#k8s-module) is now the alias for `openshift_raw` and `k8s_raw`

**Comment by tylerauerbeck** [comment]
@oybed @etsauer 

I have a small WIP around this. There's at least one small case this this module doesn't handle well because of how it relies on https://github.com/openshift/openshift-restclient-python. Templates seem to be handled fine, but in cases where we're trying to process `kind: List`, it throws an error because a list is actually a fake resource only handled by the `oc` client. I've opened https://github.com/ansible/ansible/issues/49100 to get this resolved.

Below is an example that would cause the applier to break if we made this change now. I think it's probably best to hold off on this until this becomes available otherwise we'll break some existing functionality.
```yaml
---
apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: my-cakephp-dev
  displayName: My CakePHP Dev Project
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: my-cakephp-test
  displayName: My CakePHP Test Project
```

In the mean time, we can start looking at `oc_process`. Have we asked what the roadmap looks like for this?
