### ISSUE TITLE
Recommended way to pass Template parameters when running playbook

### ISSUE THREAD

**Issue by donovanmuller** [redhat-cop/openshift-applier#5]
What is the recommended way of passing Template params when running the playbook? I.e. at playbook execution time.

Currently you can specify Template parameters in the `...-params` file pointed to by the `params` property in `inventory/group_vars/all.yml`. So using the example below:

```yaml
---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: test
    template: "{{ inventory_dir }}/../files/projects/test-template.yml"
    params: "{{ inventory_dir }}/../files/projects/test-params"
```

`{{ inventory_dir }}/../files/projects/test-params` can contain my Template parameters to be used when processing the Template.

How could you allow for specifying these parameters when running the playbook?
I.e. when running from command line or even via AWX/Tower.

**Comment by oybed** [comment]
@donovanmuller The `openshift-applier` does not support supplying / passing individual parameters, or a runtime override of param files, as this isn't necessarily the use case it is meant for. The primary purpose for the `openshift-applier` is to apply a collection of templates with a corresponding collection of parameters, and do so in a controlled fashion - i.e.: think Infrastructure-as-Code (IaC). This typically means supplying a lot more than just a few parameters and most often not maintained as runtime values (as that goes against the purpose of tracking the content). 

Having said that; we do support tweaking some existing parameters at runtime, through the use of the [make-applier-projects-unique](https://github.com/redhat-cop/openshift-applier/tree/master/roles/make-applier-projects-unique) role, but this is mainly meant for PoC or testing purposes where you want to ensure the namespaces don't clash.

We are, however, interested in input on these and curious to know more about the needs you have around runtime parameters. Can you please elaborate?

**Comment by donovanmuller** [comment]
@oybed thanks for the reply.

In my case I have a collection of templates and resources that make up a specific environment.
I would like to duplicate this environment in `development`, `staging` etc. projects by using the same templates and resources but being able to change certain environment specific parameters (like namespace name etc.) via variables.

This allows me to use the same version controlled inventory files for multiple projects/environments without duplication. In my case I would like to run my `openshift-applier` inventory files from AWX/Tower and having the ability to specify parameters via Job Template variables gives me an easy way to create multiple environments by simply copying a Job Template and changing the variables.

I have came up with a rough implementation that allows me to do the following. 
Given a Project template as follows:

```yaml
apiVersion: v1
kind: Template
metadata:
  name: team-devops-template
  annotations:
    openshift.io/display-name: Team DevOps project
labels:
  template: team-devops-template
objects:
  - apiVersion: v1
    kind: ProjectRequest
    apiVersion: v1
    metadata:
      name: ${TEAM_NAME}
    displayName: ${TEAM_DISPLAY_NAME}
    description: DevOps environment for ${TEAM_DISPLAY_NAME}
parameters:              
  - name: TEAM_NAME
    displayName: Team name
    required: true      
  - name: TEAM_DISPLAY_NAME
    displayName: Human readable team name
    required: true
```

and the following `openshift_cluster_content`:

```yaml
---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: team-devops
    template: "{{ inventory_dir }}/../files/projects/team-devops.yml"
    params: "files/projects/params"
    extra_params:
      TEAM_NAME: "{{ team_name }}-devops"
      TEAM_DISPLAY_NAME: "{{ team_display_name }} DevOps"
```

`extra_params` is something I added (for lack of a better name) that allows me to use variables for the parameter values.

I can then apply this with the following:

```console
$ ansible-playbook -i inventory/hosts site.yml \
  --connection=local \
  --extra-vars \
    "team_name=test \
    team_display_name='Test project'"
```

I can create a brand new project with the same resources but different name etc. by simply changing the `extra-vars` values.

It also supports overriding existing parameter values specified in the `params` file.

**Comment by springdo** [comment]
@donovanmuller  - this would be an awesome feature of the applier. If we could pass in the `extra_params` (or whatever it's called) like that you could reduce the amount of duplication across the ansible part of the applier and the what goes in the cluster

**Comment by sherl0cks** [comment]
@oybed the big use case where this sort of thing would be handy is `namespace` vars, particularly when you reference a namespace for a rolebinding (e.g. the Jenkins rolebinding). in practice, using a role to modify these params in params files on disk hasn't really been the catch all solution we were hoping for, so I'm supportive of this type of feature.

**Comment by etsauer** [comment]
@donovanmuller I thin there is one feature in place already

This is the idea of parameter directories.

```
---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: team-devops
    template: "{{ inventory_dir }}/../files/projects/team-devops.yml"
    params: "files/projects/params/project-defs/"
```

```
$ ls files/projects/params/project-defs/
teamA teamB
$ cat files/projects/params/project-defs/teamA
TEAM_NAME=teamA-devops
TEAM_DISPLAY_NAME=Team A DevOps
$ cat files/projects/params/project-defs/teamB
TEAM_NAME=teamB-devops
TEAM_DISPLAY_NAME=Team B DevOps
```

I realize that we're missing documentation for this feature. so I've opened #17 for this.
