### ISSUE TITLE
Convert applier into native Ansible module

### ISSUE THREAD

**Issue by pcarney8** [redhat-cop/openshift-applier#66]
My suggestion would be as part of the `k8s` module, but probably could go through being opensource first:

## Current `k8s` module

```yaml
# Passing the object definition from a file

- name: Create a Deployment by reading the definition from a local file
  k8s:
    state: present
    src: /testing/deployment.yml
```

## Future `k8s` module?

```yaml
- name: Instatiate a Template by reading a template from a local file with params from variables
  k8s:
    state: present
    template: /testing/template.yml
    params: "{{ params_object }}"

- name: Instatiate a Template by reading a template and params from a local files
  k8s:
    state: present
    template: /testing/template.yml
    params: /testing/params.txt
```
